ITUSocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('poll/', include('poll.urls')),
    path('gallery/', include('gallery.urls')),
    path('', include('pages.urls')),
    path('', include('coresite.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

gallery/urls.py
from django.urls import path

from gallery.views import GalleryView

app_name = "gallery"


urlpatterns = [
    path("", GalleryView.as_view(), name="index"),
]

pages/urls.py
from django.urls import path
from pages import views

app_name = "pages"


urlpatterns = [
    path('<slug:slug>/', views.PageDetailView.as_view(), name="page"),
]

poll/urls.py
from django.urls import path

from poll import views

app_name = "poll"


urlpatterns = [
    path('<int:pk>/', views.PollStartView.as_view(), name="start"),
    path('<int:pk>/survey/', views.PollSurveyView.as_view(), name="survey"),
]

gallery/models.py
from django.db import models
from django.utils.translation import gettext as _


class Image(models.Model):
    name = models.CharField(_("Name"), max_length=255)
    file = models.ImageField(_("Image"), upload_to="gallery")

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __str__(self):
        return self.name

pages/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

from coresite.models import ContentBase


class Page(ContentBase):
    
    class Meta:
        verbose_name = _("Page")
        verbose_name_plural = _("Pages")

    def get_absolute_url(self):
        return reverse('pages:page', args=[str(self.url)])

poll/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _


class Poll(models.Model):
    name = models.CharField(_("Name"), max_length=255)
    gd_url = models.URLField(_("Survey URL"))
    active = models.BooleanField(_("Active"), default=True)
    desc = models.TextField(_("Description"))

    class Meta:
        verbose_name = _("Poll")
        verbose_name_plural = _("Polls")

    def __str__(self):
        return self.name


class Participant(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    name = models.CharField(_("Full Name"), max_length=255)
    email = models.EmailField(_("Email"))
    student_id = models.PositiveSmallIntegerField(_("Student ID"), max_length=9)

    class Meta:
        verbose_name = _("Participant")
        verbose_name_plural = _("Participants")
        unique_together = [['poll', 'email'], ['poll', 'student_id'], ['email', 'student_id']]

    def __str__(self):
        return self.name

poll/forms.py
from django import forms
from coresite.forms import FormAbstract
from django.core.validators import EmailValidator, MaxValueValidator, MinValueValidator

from poll.models import Participant


class ParticipantForm(FormAbstract):
    class Meta:
        model = Participant
        fields = ['name', 'email', 'student_id']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].validators += [EmailValidator(whitelist=['itu.edu.tr'])]
        self.fields['student_id'].widget.attrs['max'] = 999999999


class ParticipantNewForm(forms.Form):
    name = forms.CharField(label="Ad-Soyad")
    email = forms.EmailField(label="ITU Eposta", validators=[EmailValidator(whitelist=['itu.edu.tr'])])
    student_id = forms.IntegerField(label="Öğrenci Numarası", max_value=999999999)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        domain = email.split("@")[1]
        if "itu" in domain:
            return cleaned_data
        else:
            raise forms.ValidationError("Geçersiz Email")

gallery/views.py
from django.views import generic

from gallery.models import Image


class GalleryView(generic.ListView):
    template_name = "gallery.html"
    model = Image
    context_object_name = "gallery"

pages/views.py
from django.views import generic
from .models import Page


class PageDetailView(generic.DetailView):
    model = Page
    context_object_name = "page"
    slug_field = "url"
    template_name = "page.html"

poll/views.py
from urllib.parse import splitquery

from django.views import generic
from django.shortcuts import redirect

from poll.models import Poll, Participant
from poll.forms import ParticipantForm, ParticipantNewForm


class PollStartView(generic.FormView):
    template_name = "poll_start.html"
    form_class = ParticipantNewForm

    def get_success_url(self, *args, **kwargs):
        return "/poll/" + str(self.kwargs['pk']) + "/survey/"


class PollSurveyView(generic.DetailView):
    template_name = "poll_survey.html"
    model = Poll

    def get_context_data(self, *args, **kwargs):
        context = super(PollSurveyView, self).get_context_data(*args, **kwargs)
        obj = self.get_object()
        try:
            context['gd_url'] = splitquery(obj.gd_url)[0]
        except Exception:
            context['gd_url'] = obj.gd_url
        return context

templates/gallery.html
{% extends "base.html" %}

{% load static %}
{% load thumbnail %}

{% block body %}
<div class="sub-header">
	<div class="container sub-container">
		<div class=" col-sm-8 col-sm-offset-2 col-xs-12">
			<div class="row">

				<div class="sub-title">
					<span class="head">
                        Galeri
					</span>
					<div class="col-sm-8 col-sm-offset-2">
						<p>
													</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="subheader-background">
        <img src="{% static 'img/slider_img_1.png' %}" alt="">
	</div>
</div>
<section class="gallery">
 	 <div class="container">
		  <div class="row">
			  <div class="smo-gallery" itemscope="" itemtype="http://schema.org/ImageGallery">
                  {% for image in gallery %}
                		<figure class="col-sm-3 col-xs-6 gallery-item" itemprop="associatedMedia" itemscope="" itemtype="thumbnail">
                            <a href="{{ image.file.url }}" itemprop="contentUrl" data-size="800x532">
                                {% thumbnail image.file "400x400" quality=75 as im %}
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="background-image:url({{ im.url }})" itemprop="thumbnail" alt="{{ image.name }}">
                                {% endthumbnail %}
							  </a>
						</figure>
                    {% endfor %}
                </div>
		  </div>
	  </div>
 </section>
{% endblock body %}

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{{ block.super }} - Anasayfa
{% endblock title %}

{% block body %}
<div class="banner">
	<div class="container">
		<div class="banner-content text-center">
			<div class="logo-cup">
                <img src="{% static 'img/odul-cup.png' %}" alt="">
			</div>
			<div class="start-rate">
                {{ poll.name }} {% if poll.active %}Katılımı Devam Etmektedir{% else %}Sona Ermiştir{% endif %}
			</div>
			<div class="lead">
				<p>
                {{ poll.desc }}
				</p>
			</div>
			<div class="join-rate-button">
                {% if poll.active %}
                <a href="{% url 'poll:start' poll.pk %}" class="btn btn-default">
					Katıl
				</a>
                {% else %}
                {% comment %}
                <a href="{% url 'poll:start' poll.pk %}" class="btn btn-default">
					Kazananları Gör
				</a>
                {% endcomment %}
                {% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock body %}

templates/page.html
{% extends "base.html" %}

{% load static %}

{% block body %}
<div class="sub-header">
	<div class="container sub-container">
		<div class=" col-sm-8 col-sm-offset-2 col-xs-12">
			<div class="row">

				<div class="sub-title">
					<span class="head">
                        {{ page.title }}
					</span>
					<div class="col-sm-8 col-sm-offset-2">
						<p>
													</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="subheader-background">
        <img src="{% static 'img/slider_img_1.png' %}" alt="">
	</div>
</div>
{{ page.body|safe }}
{% endblock body %}

templates/poll_start.html
{% extends "base.html" %}

{% load bootstrap %}

{% block body %}
<form enctype="multipart/form-data" method="post" style="width:400px;margin:30px auto">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="Gönder" />
</form>
{% endblock body %}

templates/poll_survey.html
{% extends "base.html" %}a

{% block body %}
<iframe src="{{ gd_url }}?embedded=true" width="100%" height="1434" frameborder="0" marginheight="0" marginwidth="0" style="margin-top:20px;">Yükleniyor...</iframe>
{% endblock body %}